"""Audit, provenance, manifest, and checksum artifacts."""

from __future__ import annotations

import json
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from nica_geofetch.models import ConversionResult, ValidationReport
from nica_geofetch.validation import sha256_file


def _write_json(path: Path, value: Any) -> Path:
    path.write_text(
        json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return path


def write_audit_reports(
    output_directory: Path,
    reports: list[ValidationReport],
    conversions: list[ConversionResult],
) -> tuple[Path, Path]:
    """Write equivalent machine-readable and human-readable validation reports."""

    audit_json = output_directory / "audit_report.json"
    audit_markdown = output_directory / "audit_report.md"
    _write_json(
        audit_json,
        {
            "project": "Nica-GeoFetch",
            "provider": "ineter-pfafstetter",
            "dataset_id": "ineter-pfafstetter-2025",
            "reports": [report.to_dict() for report in reports],
            "conversions": [conversion.to_dict() for conversion in conversions],
        },
    )
    lines = [
        "# Nica-GeoFetch audit report",
        "",
        "Institutional source data is third-party material and is not covered by "
        "the Apache-2.0 software license.",
        "",
        "| Level | Valid | Placemarks | Polygon features | Errors | Warnings | SHA-256 |",
        "|---:|:---:|---:|---:|---:|---:|---|",
    ]
    for report in reports:
        errors = sum(issue.severity == "error" for issue in report.issues)
        warnings = sum(issue.severity == "warning" for issue in report.issues)
        lines.append(
            f"| {report.level} | {'yes' if report.valid else 'no'} | "
            f"{report.placemark_count} | {report.polygon_feature_count} | "
            f"{errors} | {warnings} | `{report.sha256}` |"
        )
    lines.extend(["", "## Findings", ""])
    for report in reports:
        lines.append(f"### Level {report.level}")
        if not report.issues:
            lines.append("")
            lines.append("No validation findings.")
        for issue in report.issues:
            suffix = f" ({issue.feature_name})" if issue.feature_name else ""
            lines.append(f"- **{issue.severity} / {issue.code}:** {issue.message}{suffix}")
        lines.append("")
    audit_markdown.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return audit_json, audit_markdown


def write_source_manifest(
    output_directory: Path,
    reports: list[ValidationReport],
) -> Path:
    """Record reproducible source identities without granting data rights."""

    sources = [
        {
            "provider": "ineter-pfafstetter",
            "dataset_id": "ineter-pfafstetter-2025",
            "level": report.level,
            "official_source_url": report.source_url,
            "local_raw_file": report.source_path.relative_to(output_directory).as_posix(),
            "sha256": report.sha256,
            "validated_utc": report.checked_utc,
            "attribution": (
                "Source: INETER, national hydrographic units adjusted to Pfafstetter, 2025."
            ),
            "license_status": "No explicit open-data license identified",
            "redistribution_status": (
                "Institutional clarification required before public redistribution"
            ),
        }
        for report in reports
    ]
    return _write_json(
        output_directory / "source_manifest.json",
        {
            "schema_version": 1,
            "software_license": "Apache-2.0",
            "software_license_scope": "Nica-GeoFetch software and synthetic fixtures only",
            "sources": sources,
        },
    )


def write_provenance_summary(
    output_directory: Path,
    reports: list[ValidationReport],
    conversions: list[ConversionResult],
) -> Path:
    """Write a concise transformation and rights summary."""

    lines = [
        "# Provenance summary",
        "",
        "Generated by Nica-GeoFetch 0.1.0 using provider `ineter-pfafstetter`.",
        "Source files were validated as XML vector KML, normalized to EPSG:4326, "
        "and converted outputs were reopened before inclusion.",
        "",
        "The source institution is INETER. Converted files are not represented as "
        "official INETER products. No explicit open-data license was identified; "
        "obtain institutional clarification before redistributing complete copies.",
        "",
        "## Levels and outputs",
        "",
    ]
    by_level = {item.level: item for item in conversions}
    for report in reports:
        outputs = ", ".join(sorted(by_level[report.level].outputs))
        lines.append(
            f"- Level {report.level}: {report.polygon_feature_count} polygon features; "
            f"source SHA-256 `{report.sha256}`; outputs: {outputs}."
        )
    path = output_directory / "provenance_summary.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_checksums(
    output_directory: Path,
    paths: Iterable[Path] | None = None,
) -> Path:
    """Write SHA-256 values keyed by paths relative to the workflow directory."""

    checksum_path = output_directory / "checksums_sha256.json"
    if paths is None:
        candidates = [
            path
            for path in output_directory.rglob("*")
            if path.is_file()
            and path != checksum_path
            and path.name != "nica_geofetch_results.zip"
            and ".part" not in path.name
        ]
    else:
        candidates = list(paths)
    values = {
        path.relative_to(output_directory).as_posix(): sha256_file(path)
        for path in sorted(candidates, key=lambda item: item.as_posix())
    }
    return _write_json(checksum_path, {"algorithm": "SHA-256", "files": values})
